### ISSUE TITLE
Append JANA_PLUGIN_PATH from command line or API

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#134]
Maybe it is already implemented, but can we do something like this: 

```bash
jana --append_plugin_search_path=my_path
```

the same with python API, c++ API?

It is sometimes difficult to mess with environment variables (take CLion as an example which everybody use) and would be MUCH easier if such things would be possible through command line also

**Comment by nathanwbrei** [comment]
In principle, for every environment variable JANA uses internally, there should be a corresponding parameter that is predictably named (e.g. JANA_PLUGIN_PATH => jana:plugin_path). In practice, we can add a `jana:plugin_path` parameter right away, but I'm hesitant to do that for the others (mostly calibrations and geometry stuff) because these were imported from JANA1 and I don't understand them well enough yet to thoroughly test them. One interesting question: if both a parameter and an environment variable are provided, and they differ, which should JANA use?

**Comment by faustus123** [comment]
I agree that we should add the plugin path now as it will likely be used a lot.

We should always take the config. parameter over the envar.

**Comment by nathanwbrei** [comment]
Quick question:
$JANA_PLUGIN_PATH is colon-separated, but vector<string> JANA parameters are comma-separated. Do we want the `jana:plugin_path` parameter to be colon-separated or comma-separated?

**Comment by faustus123** [comment]
Hmmmm.. how hard is it to make it accept either? You don't find colons in directory names so use a colon delimiter if the string contains a colon and a comma delimiter otherwise.  I don't think directory names are allowed to have colons (it would screw up every PATH envar if that were the case).

**Comment by nathanwbrei** [comment]
Before you replied, I picked colon separators. Seeing paths separated by commas just looked so wrong to me.

**Comment by faustus123** [comment]
Sounds good.

So is this resolved now and can be closed?
