### ISSUE TITLE
Allow option to build static or shared libraries

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/JANA2#137]
Currently, JANA2 installs static libraries (e.g. `libJANA.a`). Downstream plugins are also compiled as static libraries (e.g. `libBEMC.a`).
- This results in some inefficiency since some symbols are stored in duplicate (about a third of symbols in `libBEMC.a` is also in `libJANA.a`). This amount of overlap would likely extent to all algorithms, leading to a potentially sizeable impact.
- This prevents modifications to JANA2 code without also recompiling all downstream plugins. This may have operational impacts.

I am not sure if there are specific reasons (beyond expediency) why static libraries were originally chosen, but allowing for the user to choose `-DBUILD_SHARED_LIBS=ON` may allow for operational optimization. This may apply similarly to downstream EICrecon reconstruction plugins.

**Comment by faustus123** [comment]
We should have it as a user option. I think the main reason it is static now is due to some paranoia I had many years ago about getting different results because the LD_LIBRARY_PATH was accidentally pointing to an older version and it would not be at all obvious to the user that this was going on. Static libraries are much bulkier and do lead to the issues you describe, but you were at least a little less dependent on the environment.

**Comment by nathanwbrei** [comment]
I'm adding this to the v3.0.0 milestone, in which we break CMake in a bunch of places all at once.
