### ISSUE TITLE
Filename mismatch about "JFactory" generator

### ISSUE THREAD

**Issue by cissieAB** [JeffersonLab/JANA2#153]
If we check the "JFactory" generator in `scripts/jana-generate.py` (https://github.com/JeffersonLab/JANA2/blob/master/scripts/jana-generate.py#L970), the generated files should be named as `JFactory_{jobject_name}_tag.cc` and  `JFactory_{jobject_name}_tag.h`.
This is how it worked out on the real system now.

However, according to the `doc/Tutorial.md` and `src/examples/Tutorial`, the filenames are `{jobject_name}.cc` and `{jobject_name}.h`.

The mismatch influences a certain amount of contents in `Tutorial.md` and codes under `src/examples/Tutorial`. It's misleading when people reading the tutorials.

As I am uncertain which version of the filename is correct, I sent this issue for your decision. Either we need to change the `jana-generate.py` or we need to update all the tutorial related contents. Once you decided the way, you can assign the task to me. 

Thanks a lot for your time and consideration! @nathanwbrei @faustus123

**Comment by nathanwbrei** [comment]
The JFactories should always live in `JFactory_{jobject_name}_{tag}.h`. It's the JObjects (which the JFactories need) that live in `{jobject_name}.h`. Where in the tutorial does this appear to diverge?

**Comment by cissieAB** [comment]
> The JFactories should always live in `JFactory_{jobject_name}_{tag}.h`. It's the JObjects (which the JFactories need) that live in `{jobject_name}.h`. Where in the tutorial does this appear to diverge?

Ref: https://github.com/JeffersonLab/JANA2/blob/master/docs/Tutorial.md#organizing-computations-using-jfactories

Start from running 
```jana-generate.py JFactory SimpleClusterFactory Cluster```, 

the codes generated mismatched the Tutorial.md and `src/examples/Tutorial`. 

```
//// =================== in the tutorial ===================
#include "Hit.h"
// ...

void SimpleClusterFactory::Process(const std::shared_ptr<const JEvent> &event) {

    auto hits = event->Get<Hit>();

    auto cluster = new Cluster(0,0,0,0,0);
    for (auto hit : hits) {
        cluster->x_center += hit->x;
        cluster->y_center += hit->y;
        cluster->E_tot += hit->E;
        if (cluster->t_begin > hit->t) cluster->t_begin = hit->t;
        if (cluster->t_end < hit->t) cluster->t_end = hit->t;
    }
    cluster->x_center /= hits.size();
    cluster->y_center /= hits.size();

    std::vector<Cluster*> results;
    results.push_back(cluster);
    Set(results);
}
```

```
//// Real code: JFactory_SimpleClusterFactory_Cluster.cc
void JFactory_SimpleClusterFactory_Cluster::Process(const std::shared_ptr<const JEvent> &event) {

    auto hits = event->Get<Hit>();

    auto cluster = new Cluster(0,0,0,0,0);
    for (auto hit : hits) {
        cluster->x_center += hit->x;
        cluster->y_center += hit->y;
        cluster->E_tot += hit->E;
        if (cluster->t_begin > hit->t) cluster->t_begin = hit->t;
        if (cluster->t_end < hit->t) cluster->t_end = hit->t;
    }
    cluster->x_center /= hits.size();
    cluster->y_center /= hits.size();

    std::vector<Cluster*> results;
    results.push_back(cluster);
    Set(results);
}

```

More examples like that.

**Comment by nathanwbrei** [comment]
Oh I understand now. 
There's actually a couple of things about the jana-generate output you pasted that are bothering me, so let me explore this for a bit on my own. Don't worry about trying to fix it just yet. I suspect both the tutorial and jana-generate are going to have to change a little bit.

**Comment by nathanwbrei** [comment]
Factories are uniquely identified by output type (e.g. Cluster) and tag (e.g. "simple" or ""). (At least for now...) This should be reflected in the naming convention. Convincing users to follow a naming convention from the start is a good idea. I wrote the tutorial first, and then jana-generate. The tutorial does not use or discuss the naming convention and I think it really should.

There are three different naming conventions that we could follow:

1. The standard Java naming convention:  SimpleClusterFactory. This makes the most intuitive sense for people with a CS background, which is why I used it in the tutorial. However, it looks really awkward in practice because a) it's not clear which part of the name corresponds to the type vs the tag, and b) there's no predictable order to the files in the file picker. Example: `CalorimeterOnlyDEventRFBunchFactory` produces `DEventRFBunch` objects tagged `CalorimeterOnly`. 

2. The GlueX naming convention, which is `${OBJECTTYPE}_factory_${TAG}`. This differentiates between the object type and tag nicely, and looks super nice in the file picker because first it shows the JObject, followed by the different implementations of the algorithm that produce that JObject.  Ex: `Cluster_factory_Simple`, `(D)EventRFBunch_factory_CalorimeterOnly` 

3. The convention that jana-generate is using right now. (which is `JFactory_Cluster`, or `JFactory_Cluster_Simple` except that's not the output you were getting, because the tutorial is out of date about what args jana-generate takes) The only benefit is that the different parts are ordered from general to specific, which is satisfying to a theoretician but makes for a worse file picker experience.

One complication is that we like to prefix our classnames with a single letter to indicate what code base they are a part of (essentially a DIY lightweight namespace). So everything in JANA is prefixed with a "J" and everything in halld_recon is prefixed with a "D". Using this rules out option (3) because it forces the wrong prefix, and it conflicts a little bit with (1). On the other hand, (2) works quite nicely because the prefix originates on the jobject and transfers over to the factory automatically.

I guess I'm arguing that we should tweak jana-generate to use GlueX-style naming conventions, and update the tutorial to use those and explain them to the user.

**Comment by nathanwbrei** [comment]
It's probably a good idea to make this change soon though, since EIC users will be directed to this tutorial pretty soon and we don't want them to experience the same confusion.

**Comment by nathanwbrei** [comment]
The arguments to `create_jfactory` are `jobject_name` and `tag`. In the tutorial example, since the JObject type is `Cluster`, we should be calling it like `jana-generate.py JFactory Cluster` or `jana-generate.py JFactory Cluster Simple` instead.

A `JFactoryT<ObjectT>` promises that it can build `ObjectT`s. We don't call the factory directly, we call `JEvent::Get<ObjectT>(tag)` which calls the factory for us. Each different subclass of JFactoryT has its own tag, which is unique for that `ObjectT`. We often have many different factories that provide the same `ObjectT`. Sometimes we need the data from a specific one, in which case we call `JEvent::Get<ObjectT>("MyImpl")`. Usually we don't, and we would rather have the freedom to swap different implementations in and out; in this case we call `JEvent::Get<ObjectT>("")` which is treated as the default implementation. To swap in a different JFactory we have a feature called "default tags": by setting the parameter `deftag:ObjectT=tagName` you are telling JANA that `JEvent::Get<ObjectT>("")` should redirect to `JEvent::Get<ObjectT>("tagName")`. 

While this concept for tags is a little weird, it is simple, efficient, and does ~80% of the things that you'd want it to. The GlueX people are quite happy with it, although some EIC people have a few doubts. These doubts are described in Issue #147. I have a proof of concept that extends the concept of tags in order to address the remaining 20%, though it needs a bit more refinement before I present it to David.

**Comment by cissieAB** [comment]
> The arguments to `create_jfactory` are `jobject_name` and `tag`. In the tutorial example, since the JObject type is `Cluster`, we should be calling it like `jana-generate.py JFactory Cluster` or `jana-generate.py JFactory Cluster Simple` instead...

The command
```
jana-generate.py JFactory SimpleClusterFactory Cluster
```
is taken from the current `Tutorial.md`. We really need to go over the tutorial again...
<img width="1004" alt="Screen Shot 2022-08-24 at 22 29 05" src="https://user-images.githubusercontent.com/40411327/186560431-e4b7b3fe-7ee8-41cf-86f3-9baa1988cfef.png">

**Comment by nathanwbrei** [comment]
Understood, the tutorial is definitely out of date right there. Also, it is becoming clear that someone (probably me!) needs to update it to explain the filename convention, and add more information about how tags work.

**Comment by cissieAB** [comment]
> Understood, the tutorial is definitely out of date right there. Also, it is becoming clear that someone (probably me!) needs to update it to explain the filename convention, and add more information about how tags work.

To make up my latest reply, if we call `jana-generate.py` the other way, the generated code will be totally different. We need to double check whether the generated code meets our expectation.

**Comment by nathanwbrei** [comment]
Keeping jana-generate.py in sync with examples/Tutorial has been a pain for a while. Believe it or not, both David and I have followed the tutorial using jana-generate a number of times. Every time we find something that could be improved.

**Comment by cissieAB** [comment]
> Keeping jana-generate.py in sync with examples/Tutorial has been a pain for a while. Believe it or not, both David and I have followed the tutorial using jana-generate a number of times. Every time we find something that could be improved.

Good luck! Sympathy on you :P
The thing is, we do not need many details in the tutorial, and it will make things easier for both the code keeper and the reader.

**Comment by cissieAB** [comment]
Working on it. I guess I need to update `jana-generate.py` more according to the CI runs.
