### ISSUE TITLE
More informative error output if factory is not found

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#22]
Not the highest priority, but nice to have. 

Now if factory is not found, you get something like: 

```
output.root:/
ERROR: No factory found for type = minimodel::McFluxHit, tag = ""
  1 events processed  0.0 Hz (2.0 Hz avg)             Event processing ended. 
```

Would be nice to know at least what plugin requested that data.

**Comment by nathanwbrei** [comment]
I agree. This wouldn't be a simple change, though. I'll keep it in mind.

**Comment by nathanwbrei** [comment]
The change would require two parts:

1. Adapting JPluginLoader and JTopologyBuilder to track plugin names and attach them to Factories
2. Modifying JEvent to throw an exception when a Factory is missing, and catch it upstream. (Currently the JEvent itself does the terminating, which feels wrong for a variety of reasons)

I have a prototype for the next-gen JEvent in the works, and it is much easier to incorporate (2) there than in the existing JEvent, assuming nobody needs this anytime soon.

**Comment by nathanwbrei** [comment]
Plugin name, source/processor name, and parent factory name/tag are all attached to the JException now, along with a backtrace and a std::exception_ptr to any user exception which is not a JException. The name+tag of the factory which could not be found goes in the error message instead. This happens automatically, so you can throw a JException in your code and my code will fill in the details so that it can generate a somewhat helpful error message. This hopefully gives you some motivation to throw a JException instead of a std::runtime_error. This is all on feature_jstatus, by the way.
