### ISSUE TITLE
Question about std::move in JEvent->Insert

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#25]
A question rather than an issue. 

So now there is no reason to use std::move here:

```c++
jana_event->Insert(std::move(result_particles));
```

Move will not "work" there anyway, right?

**Comment by nathanwbrei** [comment]
You're right. Insert() takes a const ref and then manually appends each item to the back of the Factory.

We could add a JEvent::Put() which overwrite the factory objects instead of append them, and that would benefit from the std::move. It would be little less flexible, if that matters. I doubt there will be a big performance difference either way.
