### ISSUE TITLE
Feature Request: PLUGINS_TO_IGNORE

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/JANA2#27]
Thomas suggested a config. parameter that allows you to ignore certain plugins. This is useful for mcwrapper run jobs that may need to run recon and analysis separately but would use the same JANA config file. The second invocation would explicitly ignore the danarest plugin.

**Comment by DraTeots** [comment]
While I like the idea in general, the particular reason (running the same file) smells like something artificial....

**Comment by nathanwbrei** [comment]
What semantics are we aiming for when we have contradictory values in the config file vs the cmd line args? I would have assumed that "-Pplugins=a,b" would override "plugins   a,b,c" so that "c" never gets run. If this is the case, PLUGINS_TO_IGNORE should be unnecessary.

On the other hand, if our list of plugins accumulates values from both the config file and the arg list, then PLUGINS_TO_IGNORE becomes ugly and complicated because we have to consider both whitelists and blacklists from both the config file and the command line. This becomes conceptually inconsistent because if you have 'accumulate' semantics for inclusion, you'll need 'override' semantics to undo an exclusion in the config file. There isn't one obviously correct and intuitive formula, either:

{inclusions_configfile U inclusions_cmdlineargs} \ {exclusions_configfile U exclusions_cmdlineargs}
{inclusions_configfile \ exclusions_cmdlineargs} U {inclusions_cmdlineargs \ exclusions_cmdlineargs}
{inclusions_configfile U inclusions_cmdlineargs} \ {exclusions_cmdlineargs}
{inclusions_configfile U inclusions_cmdlineargs} \ {{exclusions_configfile U exclusions_cmdlineargs} \ inclusions_cmdlineargs}
etc

**Comment by faustus123** [comment]
1. Command line should always override config file
2. Multiple config files should be processed in order so ones specified later on the command line override ones specified earlier
3. Setting a config. parameter at any point will replace and not add to the parameter if already set. 
4. The PLUGINS_TO_IGNORE should be applied after all config parameters have been set and just before attaching the plugins.

Thus, someone could specify PLUGINS_TO_IGNORE first and the actual plugin to be ignored second (or vice versa). The user's intentions are considered clear by the presence of PLUGINS_TO_IGNORE being set from anywhere.

**Comment by nathanwbrei** [comment]
I fully agree with your points 1-4. But what is the use case for PLUGINS_TO_IGNORE, then?

Is it just so that you can say 
plugins     a,b,c,d,e,f,g,h
-Pplugins_to_ignore c

instead of 
plugins a,b,c,d,e,f,g,h
-Pplugins a,b,d,e,f,g,h
?

**Comment by faustus123** [comment]
You are absolutely correct that there is already path to do this and that it is probably cleaner than using a separate "ignore" parameter. However, this was a user request that they somehow felt fit their workflow better. It seemed like it would not be too hard to implement or intrusive to our design so that the cost to us was minimal. Maybe it is more complicated than I am imagining(?)

**Comment by nathanwbrei** [comment]
Not at all, I was just wondering if I was missing something. It's an easy change.
