### ISSUE TITLE
Aceess to JApplication interface from JFactory

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#30]
I have a plugin with a Factory. The plugin has parameters that are used for the factory. So this Factory has access to JApplication and JParameter manager only during process (through ```event->GetJApplication()```)

1. 

```c++
void SmearingFactory::Process(const std::shared_ptr<const JEvent> &event) {
    using namespace fmt;
    using namespace std;

    std::call_once(read_parameters_once_flag, [this](){
        pm->SetDefaultParameter("eic_smear:verbose", this->verbose, "Plugin output level. 0-almost nothing, 1-some, 2-everything");
        pm->SetDefaultParameter("eic_smear:detector", this->detector_name, "Detector name: beast, jleic, zeus");
    });
```

This works but that text in the beginning of the Process function is kind of not belong to the process. 

2. Create special constructors like 

```c++
/// This class is temprorary here while JANA2 API is getting to perfection.
/// Here we just list JFactories defined in this plugin
struct OpenCharmInputParticleGenerator:public JFactoryGenerator {

    OpenCharmInputParticleGenerator(JApplication *app) {
        _app = app;
    }

    void GenerateFactories( JFactorySet *factory_set) override {
        factory_set->Add(new SmearingFactory(_app->GetJParameterManager()));
    }

private:
    JApplication *_app;
};
```

Which also creates unnecessary code

**Comment by nathanwbrei** [comment]
I'm skeptical about event->GetJApplication() in general. It makes perfect sense to pass the ParameterManager and ServiceLocator as args to JFactory::Init() instead. Before I do so, let's discuss implementation:

1. Should we do `JFactory::Init(JApplication* app);` or `JFactory::Init(JParameterManager* pm, JServiceLocator* sl)`? The former is more future-proof, but also allows users to shoot themselves in the foot more. Slight preference towards future-proofness at the moment. Also more consistent with InitPlugin(), etc.

2. Can we use shared_ptr instead of raw pointer? Conceptually it should be shared_ptr. Main problem is that using shared_ptr implies that we don't keep a bunch of raw pointers hanging around, which we do. Do we migrate all the raw pointers to shared pointers, hack the thing, or postpone for now?

3. What is the intended lifetime of any data that gets stored onto the JFactory from here, and how can we enforce this? My first thoughts are to strongly encourage users to save parameters as values rather than storing a pointer to JParameterManager and thus having them endure for the entire life of the JFactory, a.k.a. across multiple events and runs. Services are already shared_ptr, which is correct semantically but may degrade performance if the user frequently dereferences them inside JFactory::Process() as opposed to JFactory::ChangeRun().

**Comment by DraTeots** [comment]
1. Can JServiceLocator provide... JApplication? 

2. Spent long time thinking/reading/researching about it some time ago (when had to switch back to Jana and C++ in general again). Whatever I did read, [this answer](https://stackoverflow.com/a/6675673/548894) looks like the most concise and reasonable answer for me. Even if you'll be able to get rid or the raw pointers 

3. Could I propose to sit with you after the Paris meeting and try to rewrite the code we have right now? I think, this would help synchronize what you think users should do, and what users don't know how to do. For example, I tempted to change the data produced in one factory by the other factory. Felt like it  definitely not how Jana is designed, still copying the same objects to have all the fields except 2 looks as a worse decision

**Comment by nathanwbrei** [comment]
1. Only issue is that ServiceLocator provides shared_ptr, of which JApplication is not. I'm now thinking that JParameterManager should be used via a shared_ptr, and JApplication via a raw pointer, as per (2). 

2. Beautiful, I like it. I'm so dissatisfied with smart pointers, still feel like I just don't "get" how to use them. Working with Rust is like a breath of fresh air because thinking carefully about ownership leads to code that compiles and looks right, whereas with C++ I'm just going around in circles. 

3. Of course! In the meantime I'll try to think of a solution to the problem you're describing.

**Comment by DraTeots** [comment]
2. If you recall that email exchange with David (I still have to write an answer, yes), that was exactly... That is the problem, smart pointers just don't work. They partly make some parts less painful. But they don't provide any real answer like rust burrowing system and etc does.

**Comment by faustus123** [comment]
Just to put in my 2 cents here. I believe there really is a place for smart pointers, but I am now really concerned about using them in a environment that is supposed to implement highly efficient multi-threading. I don't see how a shared pointer can work and be thread safe without doing some kind of coordination between threads. This can kill performance if they do it during Process.

I think I am in favor of passing JApplication rather than JParameterManager and JServiceLocator primarily for the future-proof reason Nathan mentioned. I think we should consider passing it by reference as suggested in the post Dmitry pointed to. That would signal to users that it is not necessarily expected to exist beyond the current call. As he pointed out, they can still get to JApplication via JEvent at other times of needed.

**Comment by nathanwbrei** [comment]
JFactory::Init() can now access JApplication* via GetApplication(), just like JEventProcessors. There should be no reason to ever use japp for this purpose ever again.
