### ISSUE TITLE
SetTypeName and related stuff

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#33]
```c++
    /// SetTypeName is intended as a replacement to GetType(), which should be less confusing for the
    /// user. It should be called from the constructor. For convenience, we provide a
    /// NAME_OF_THIS macro so that the user doesn't have to type the class name as a string, which may
    /// get out of sync if automatic refactoring tools are used.
    // Meant to be called by user
    void SetTypeName(std::string type_name) { m_type_name = std::move(type_name); }
```

Looks like GetDemangledName has disappeared and NAME_OF_THIS hasn't appeared. 

P.S. **Building of ALL ejana event sources are failing now**

**Comment by faustus123** [comment]
I may have missed a discussion so forgive me for being out of the loop a bit. Would it be possible to give a short snippet of how this would be used so I can understand it? Especially useful would be snippets of both how it would be done with the existing system and with the proposed change.

Also, is this issue related to the failing builds of eJANA?

**Comment by nathanwbrei** [comment]
NAME_OF_THIS macro lives in Utils/JTypeInfo.h, along with demangle<T>(). JEventSource.h wasn't importing that, so I'm changing it so that it does.

**Comment by nathanwbrei** [comment]
Dmitry: SetTypeName() is optional and shouldn't be causing builds to fail. Can you provide more info?

David: SetTypeName() is tentative and very open to discussion. Basically the idea is that there is a bunch of info that all JEventSources, Processors, Factories, need to provide to the JComponentManager. Examples include plugin name and resource name. Some of these come from the user, others come from JANA itself. The existing mechanism of using virtual functions together with macros does the wrong thing by default if the user does nothing, and gives the user the opportunity to make things very confusing, e.g. provide a type name which is not actually a type name. My tentative solution is to make all of these fields be simple strings with consistent getters and setters, and tell the user via the documentation that they are required to set some of them. The rest are set by JANA afterwards, so if the user sets them it will be a no-op. One of the reasons this is tentative is because I think we can do a lot better if we split components into a frontend/backend and rejigger JEventSource/JFactoryGenerators a bit.

**Comment by DraTeots** [comment]
Lets separate issues. 

1. Compilation problems. GetType - was copied from some early Jana2 examples and then copied for new event source classes from older ones. So if it is optional now, I'll quickly fix it. 

2. NAME_OF_THIS. Actually having  ```demangle<Geant4EicEventSource>()``` is OK. Changin GetDemangledName to demangle and moving it to another file confused me (I haven't found it). And the comment stated about NAME_OF_THIS

2. API update. In general, having SetTypeName and having NAME_OF_THIS in Utils/JTypeInfo.h makes API much more clear to me. The same goes with replacement of mFactoryGenerator, and moving stuff around.
