### ISSUE TITLE
SBMS doesn't support Python3

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#36]
Can't compile JANA2 on ifarm in python3 environment. 

Unfortunately, as scons lost its popularity I believe it to be a flaw of JANA2 and related to its development.  

JANA2 ships scons3. But it opens a can of worms. One can't simply run something like:

```
python /.../jana/scons/scons.py install -j4
```

Like then I've got python2 to 3 problems like:
```
 print "looking for %s.py" % modname
                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("looking for %s.py" % modname)?
```

**Comment by nathanwbrei** [comment]
I'm thinking the time is right to support building all of JANA with just CMake. That said, we still need to support scons at a minimum until we port GlueX, and I expect David will want to support it much longer. It looks like the problem is SBMS and not scons itself, which should be reasonable to fix.

Since I've seen enough other weird transitive dependency conflicts involving python, and python2 is end-of-life anyway, I propose we migrate SBMS to python3 for the time being and plan on using CMake in the future.

**Comment by nathanwbrei** [comment]
A complication:

By default, ifarm gives me 
/apps/bin/python, which is version 2.7.5
/apps/bin/python3, which is version 3.4.3
/apps/bin/scons, which is version 2.5 (which runs on python2.7 only)

And JANA bundles scons version 3.0.1 (which runs on python2.7 and python 3.5+) 

Right now, `cd JANA; scons install` just works, but if we move SBMS to python3, everyone will have to use a venv _and_ specify the bundled scons. 

Maybe we should just finish building out cmake support and leave scons alone until someone updates ifarm.

**Comment by nathanwbrei** [comment]
SBMS should now work with both
- the old versions of python2 and scons that are default on ifarm
- a modern python3.5+ venv with the bundled scons
