### ISSUE TITLE
Is it possible not to catch exceptions? 

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#38]
Looking at #37. 
If I'm debugging jana2 in IDE, I would like IDE to catch exceptions, not jana. 

Is it possible to add some flag like: 

```
jana:raise=true
```
which would allow to propagate exceptions to a debugger? 

P.S. I know there are probably problems related to catching exceptions in worker threads.

**Comment by nathanwbrei** [comment]
CLion's debugger will catch exceptions at the site they are thrown, which is how I've been debugging this thing. You have to enable the behavior via Debug pane -> View Breakpoints (two red circles) -> Exception Breakpoints.  The only downside to this approach is that the debugger pauses when someone uses exceptions for flow control... ;)

I think adding the flag would be a reasonable thing to do though. Catch does this.

**Comment by nathanwbrei** [comment]
A complication: I assume you want to pause the debugger at the site where the exception was first thrown. The obvious implementation of this flag would pause the debugger at a generic exception handler rather than the exception source. 

This is because exceptions get caught and re-thrown at least once, in order to attach information about the originating plugin/factory/eventprocessor without relying on hidden global state. If we were correctly forwarding exceptions from worker threads, which is on my todo list, we'd rethrow again.

**Comment by DraTeots** [comment]
Yep. That is something I thought of how it is done. Thanks for clarification.

**Comment by faustus123** [comment]
FWIW, I recalled gdb breaking at exceptions regardless of wether a handler was installed. A quick search on SO shows there is a way to have this behavior (though I don't actually recall doing it?) The short answer is you should enter "catch throw" before starting the program in gdb. This is likely what CLion is doing.

I'd be hesitant myself to put in an option to disable exception handling in JANA2 unless this some scenario the gdb feature doesn't handle properly.

https://stackoverflow.com/questions/1115428/run-an-application-in-gdb-until-an-exception-occurs

**Comment by nathanwbrei** [comment]
Since the feature is both redundant and hard to implement usefully, I'm closing the ticket.
