### ISSUE TITLE
JANA2 runs infinitely after all events are processed

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#4]
It happens because of ```bool JThread::HandleNullTask(void)``` [here](https://github.com/JeffersonLab/JANA2/blob/4177586a58b18895f81a03940158baf7cd1dcf3c/src/lib/JANA/JThread.cc#L397)

returns ```true``` because
```c++
auto sNumOutstandingEvents = sEventSource->GetNumOutstandingEvents();
```
returns non zero values [here](https://github.com/JeffersonLab/JANA2/blob/4177586a58b18895f81a03940158baf7cd1dcf3c/src/lib/JANA/JThread.cc#L419)

Then I figured out that mNumOutstandingEvents probably is not decremented enough and that the only time it decrements is in ```sEvent->Release();``` && JEvent destructor. Which probably could mean that JEvent destructor is not getting fired because something may hold sharedptr or whatever... 

Here I would like an expert help to untangle it as I feel that it might be something simple and stupid

**Comment by DraTeots** [comment]
ejana should compile now

**Comment by faustus123** [comment]
I sent this to Dmitry via e-mail, but should have posted it here.

 This problem is caused by the call to event->SetJEventSource(this) at line 145 of JEventSource_jleic_geant.cc. That call increments the mNumOutstandingEvents member of the JEventSource. The SetJEventSource method is also called internally by JANA which means the counter is being incremented twice for every event, but only decremented once when the event is released.

  The quick fix is to remove this line from the JEventSource_jleic_geant.cc file (you’ll also want to remove it from the jleic_gemc_reader plugin). The better fix is for us to make this method private. This would have clued you in that it was not intended to be called outside of the JANA library.
