### ISSUE TITLE
Define output string formats

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#40]
At this point the output looks like this:
![Screenshot from 2019-12-16 11-36-52](https://user-images.githubusercontent.com/4732545/70925123-b6f3c180-1ff8-11ea-848a-3a7aa62bc54c.png)

I really like the order of tables. But there are several issues displaying them as it is now:

1. File names can be terribly long and destroy any table column length formatting
2. Some class names may be longer too (not sure if columns lengths  are automatically calculated)
3. What amount of output (stored to a log file) is going to be when working 12 hours on farm?

**Comment by nathanwbrei** [comment]
1 & 2 are a quick fix if we truncate all but the last n characters of the strings. 
3 is controlled by:
  a) The jparameter jana:extended_report, which chooses between the tabular performance ticker and the one-liner version
  b) JApplication::SetTicker(false) which will make the ticker go away entirely. We probably want this to be controlled via a jparameter as well, e.g. "jana:show_ticker". 

The main question for (3) is what the default values for these things should be. I think we should choose defaults with the unsophisticated user in mind, which in practice means showing the one-line ticker. farm jobs can turn off the ticker entirely and performance tuning runs can turn on the detailed tabular ticker. Also at some point we should consider a clearer relationship between tickers and status reports.

**Comment by DraTeots** [comment]
At this point I need to easy parsing status. Running, error, ended and care about time and number of events. Keeping it simple

**Comment by faustus123** [comment]
Dmitry: Has this issue been addressed?

**Comment by nathanwbrei** [comment]
I made the log output easier to parse. Not sure whether Dmitry's Jupyter interface has been updated to use it. I'd like to keep this issue open because there's a 'better' approach that may be possible soon. The idea is to optionally output the multi-line structured log messages (such as config parameters, components, and performance) as single-line JSON blobs.

**Comment by DraTeots** [comment]
Yes!

**Comment by nathanwbrei** [comment]
Even though I think that having the option to represent multi-line log messages as JSON blobs is really cool, I'm closing this issue for now since the original bug has been resolved and I already have a huge backlog of nice-to-have features. If a user says they really want the JSON blobs, we can revisit.
