### ISSUE TITLE
Build system ergonomics improvements

### ISSUE THREAD

**Issue by nathanwbrei** [JeffersonLab/JANA2#46]
Latest INDRA work reveals small problems with CMake setup which might confuse users.

- CMake is picking up -DJANA_HOME, but not $ENV{JANA_HOME}
- streamDet and JExample7 targets are commented out due to dependency complications
- Understanding the build directory vs the install directory is not clear from documentation
- Documentation only mentions scons

**Comment by nathanwbrei** [comment]
Discussion today with David re. ergonomics of $JANA_HOME.
Key points:

- Letting CMake automatically install to /usr/local if no $JANA_HOME or $CMAKE_INSTALL_PREFIX is specified can lead to a debugging nightmare when $JANA_HOME is then set and libjana modified. The "system-wide install" use case doesn't help jana developers and users would still need to set $JANA_HOME regardless. Easy fix: Have CMake throw an error if $CMAKE_INSTALL_PREFIX = default

- Using $JANA_HOME to determine the libjana install directory causes a nasty surprise for users who have $JANA_HOME pointing at something they don't want clobbered, such as JANA1. Easy fix: User is forced to supply JANA_HOME as a CMake variable as opposed to an environment variable. This way they are forced to make a decision as to where the install goes.

- Using $JANA_HOME inside jana-generate.py unnecessarily gets in the users' way, particularly since the script can usually infer where to find catch.hpp by looking at __file__, etc. Inferring this is complicated and ugly, but tractable.

**Comment by DraTeots** [comment]
Why not make CMake file for Jana telling where it is and etc. 
Then one could use just cmake find_package

**Comment by faustus123** [comment]
I think this is already there in the cmake/FindJANA.cmake file.

The issue Nathan is addressing here came out of a discussion we had yesterday about the role of JANA_HOME while actually building JANA. I think we were mostly in agreement that building JANA itself does not need a JANA_HOME to be specified in the environment, but does need clear installation instruction from the user on the installation location via something like CMAKE_INSTALL_PREFIX or a JANA_HOME cmake variable.

For building other packages against JANA, one likely needs a JANA_HOME envar or access to jana-config.py just so they know where to look for the FindJANA.cmake file. Let us know if you think something more than this is needed.

**Comment by DraTeots** [comment]
David, FindJANA.cmake is completely different beast. 

Actually cmake provides the functionality you are talking about for this ticket. Package configuration file and package version file. Actually providing something like FindJANA is not the cmake-right way to distribute/find packages in cmake. It is kind of a hack to find a package if it is not distributed the cmake way. 

Since cmake is intruder in our HENP world, and initially all packets where something like configure/make, people wrote a lot of FindXYZ scripts. As the result a lot of people just copy this and don't know that the-right-designed-by-cmake way even exists.

It looks like this: when you compile JANA2, you generate package-config and package-version files. So If another project wishes to use JANA2 it need only to locate the JANA2-config.cmake file and load it to get all the information it needs about package content locations. Since the package configuration file is provided by the package installation it already knows all the file locations.

Where CMake searches package configuration files? - There are couple of cmake standard locations, packet registries and finally there is CMAKE_MODULE_PATH environment variable. 

Official documentation:  
https://cmake.org/cmake/help/v3.14/manual/cmake-packages.7.html#package-layout

Here is a good explanation/tutorial:  
https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/Packaging
