### ISSUE TITLE
Segfault if object added 2 times

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#50]
It is possible to add objects 2 times (is this bug or feature?). 

In this case jana segfaults during cleanup. 

JFactoryT has

```c++
// Assuming we _are_ the object owner, delete the underlying jobjects
        if (!TestFactoryFlag(JFactory_Flags_t::NOT_OBJECT_OWNER)) {
            for (auto p : mData) delete p;
        }
```
So it tries to delete duplicated object the second time.

**Comment by faustus123** [comment]
Are you saying the mData container holds two copies of the same pointer? What is the scenario
which would lead to this?

It seems if we wanted to ensure this didn't happen we'd either have to control when pointers are added to mData or convert mData to something like a "set" before deleting. Neither seems desirable. 

More context would be helpful here.

**Comment by nathanwbrei** [comment]
I don't see any desirable use case for adding the same pointer to mData twice, so I'd classify this one as "us not preventing the user from shooting themselves in the foot". There are plenty of related ways they can shoot themselves in the same foot: they could add a pointer to a JObject which lives on the stack, or they could hang on to the same pointer as a member variable and re-add it for every event because they don't know about the PERSISTENT flag, or they could add an uninitialized pointer. The nature of C++ forces us to assume our users are somewhat careful about memory safety. At any rate, we should definitely document this behavior clearly.

**Comment by DraTeots** [comment]
More details:
I accidentally called `Insert` twice (there was some selection ifs spaghetti which did it)

Outcome:
Segfault on the end of event. 

The  problem:
In this case it was just a miracle that I found duplication so easy. As it segfaults somewhere in destruction with something that looks like can't be null. GDB shows 'delete' string as a problem, but the object shown to be not null. So there is no clue what is wrong with it.  I was lucky enough to look closely through the `mData` list to see same pointer addresses there. 

Rephrasing Nathan - "shooting themselves in the foot" even is not a problem. My concern is that after one shoots into his foot the bullet comes out of his ear.

**Comment by nathanwbrei** [comment]
I'm struggling to think of mitigations for this. Any ideas? Here are my (terrible) ideas so far:

1. Copy the JObjects instead of assuming ownership 
=> performance hit + introduces new correctness problems because users won't know the Rule of Five and C++'s default copy/move ctors will do the Wrong Thing

2. Check that pointers are unique before deletion and throw a helpfully worded JException if not
=> turns an O(n) operation into O(n lg n), run for every event, for every T extends JObject

3. Make mData be std::vector<std::unique_ptr<T>> 
=> PERSISTENT and NOT_OBJECT_OWNER flags definitely do NOT have unique_ptr semantics, so we'd need to store them separately. Plus we'd need to either convert std::unique_ptr back to a raw pointer for JEvent::Get (which is conceptually ugly plus a performance hit), or we'd need to convert all downstream code to expect std::vector<std::unique_ptr<T>>, which is ugly, a whole lot of work, and confusing to the user. 

4. Take construction of JObjects out of the hands of the user entirely. Merely allow them to set the values on a JObject reference they don't control, similar to std::queue::peek(). This one looks the most promising actually - it's essentially a builtin JResourcePool<T>.

**Comment by DraTeots** [comment]
Lets look in another direction. Is there any not performance hitting way to detect such problems/segfaults and make sane error messages?

**Comment by DraTeots** [comment]
I can actually do this on ejana level. I have some segfault handler

**Comment by nathanwbrei** [comment]
Closing this issue as WONTFIX as this behavior is an obvious consequence of our memory ownership policy. This should documented more clearly, but we'll do this as part of issue #49.
