### ISSUE TITLE
Make debug plugin loading ON by default

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#66]
Why not enable debug_plugin_loading by default? Imagine user experience dlopen problems and coming on Slack to us. Instead of having dlopen failure log from the user, I first have to frustrate him more, asking to go and run one more time with some strange additional flags...

**Comment by nathanwbrei** [comment]
Agreed. I think I already made this change somewhere. I'll make sure it is in the next tagged release.

**Comment by nathanwbrei** [comment]
The search paths visited by JPluginLoader are all shown in the case of plugin loading failing, as of commit 372e101. I just re-added the dlopen error to this, so that we don't need debug_plugin_loading at all anymore. Be advised that the dlerror is neither particularly informative nor well-formatted.
