### ISSUE TITLE
Provide help for JANA flags and logging

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#67]
Jana prints something about its flgs on `jana --help`. But there is nothing about logging and stuff like "log:debug"

There is no list of flags on the webpage at all.

**Comment by faustus123** [comment]
Referencing Dmitry's e-mail reply not logged here:

Sorry you are having issues with the plugins. The reasons for having a default behavior that does not print detailed messages when a plugin fails to attach are mostly historic. I think you are correct that we should make the default behavior be more verbose and allow the user to turn that off only in the rare case when they may wish to. We'll make that change available in the next minor version tag.

We should also make it easy to list all of the JANA defined config. parameters in the jana --help printout. That should be straight forward to implement. Nathan and I will discuss  the best way to get it into the documentation in a way that ensures it does not go stale quickly.  Listing user defined parameters is a little harder due to the on-demand nature of JANA, but that does not appear to be what you are concerned about at the moment.

We'll look into the logger config. parameters as well to figure out why they are not doing what you expect.

**Comment by nathanwbrei** [comment]
The jana CLI args and flags are in fact documented. See the section "Running JANA" at 
https://jeffersonlab.github.io/JANA2/Installation.html

However, they clearly need to be made easier to find. The log levels are not documented anywhere yet.
