### ISSUE TITLE
MyProject-targets.cmake is not found

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#68]
Hi all!

I'm having problem using generated MyProject-targets.cmake because of CMake 3.15 (again). 

```
CMake Error at /home/romanov/eic/jana/jana-v2.0.2/lib/cmake/JANA/JANAConfig.cmake:31 (include):
  include could not find load file:

    /home/romanov/eic/jana/jana-v2.0.2/lib/cmake/JANA/MyProject-targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.15)
```

I would believe, that this should be fixed in a new version. But is it a good time to create a 2.0.3 release? There where couple of good changes...

**Comment by nathanwbrei** [comment]
A tagged release is coming. 

For now, there are several different things going on in your error message:

1. You are trying to run a project plugin as though it were a standalone plugin. Generate a standalone plugin instead, and this will go away. Project plugins assume your plugin lives inside an existing CMake source tree such as ejana. Standalone plugins create their own CMake project with their own findJANA, findROOT, cmake_min_required, etc.

2. The actual CMake error you are getting is because CMake is picking up JANAConfig.cmake instead of findJANA.cmake. The former doesn't quite work yet, and nothing else is using it. 

3. There is no problem with the cmake minimum required version. This is the third place you've complained about the cmake min required version. There is no regression.

**Comment by DraTeots** [comment]
Ok, looks like it is not the minimum required version. There is a bug with 

JANAConfig.cmake has
```
include("${CMAKE_CURRENT_LIST_DIR}/MyProject-targets.cmake")
```
But there is no such file when JANA is installed

**Comment by nathanwbrei** [comment]
Yes. But the real problem is that you are trying to compile an incomplete CMake project.

**Comment by nathanwbrei** [comment]
I feel like I've fixed the "MyProject-targets.cmake" bug about 5 times, but it finally made it into master as of commit 284744325cad1456a87868eca3b2c48e4ff68463.
