### ISSUE TITLE
Tagged JFactoryGeneratorT

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#73]
Lets have JFactoryGeneratorT with tag? 
As tag is given when a Factory is created thus it should be up to JFactoryGeneratorT?

The idea is to have just a single function to process, but also to have a tag. How I believe it would be convenient:

```c++
void InitPlugin(JApplication *app)
{ 
    // ...
    app->Add(new JFactoryGeneratorT<JFactoryT<SomeType>>("my_tag"));  // < ===
}

/// Produces McGeneratedParticle
template<>
void JFactoryT<SomeType>::Process(...) {/*...*/}

```

**Comment by faustus123** [comment]
Let me make sure I understand the use case. It looks like you are creating a factory that does not have any actual algorithm, but only serves as a container for type "SomeType". This is useful if the types are generated from the event source. So is the point of this change to allow the event source to provide multiple flavors of "SomeType"?

**Comment by nathanwbrei** [comment]
I'm also curious as to the use case.  
Personally I feel that what we are currently doing doesn't feel quite right. At the moment we set the tag as a JFactoryT parent ctor arg, and don't put any requirements on the child ctor args, which enforces tag constness. On one hand, tags feel weird, because in practice we pretty much always have a one-to-one relationship between tag name and class name, so they seem redundant. On the other hand, the user is already perfectly free to instantiate multiple factories of the same class but with different tags. When they do so, they will most likely want to pass additional ctor args so that the two instances of the same class are functionally different. For this, however, the JFactoryGeneratorT template would not suffice; they'd want to create a custom generator. 
For instance:
```
class MyTrackingFactory : public JFactoryT<RecoTrack> {

   double m_aggressiveness;
   // Suppose we want to run the exact same algorithm with different 
   // aggressiveness params side-by-side!

public:
   MyTrackingFactory(std::string tag, double aggressiveness) 
      : JFactoryT(JTypeInfo::demangle<T>(), tag), m_aggressiveness(aggressiveness) {}
   // ...
};

class MyTrackingFactoryGenerator : public JFactoryGenerator {
   void GenerateFactories(JFactorySet *factory_set) override {
         // NOTE: Ideally we'd obtain a range of params from JParameterManager,
         // but note we don't have access to JApplication from here        
	factory_set->Add(new MyTrackingFactoryGenerator("gentle", 1.0));
	factory_set->Add(new MyTrackingFactoryGenerator("moderate", 5.0));
	factory_set->Add(new MyTrackingFactoryGenerator("aggressive", 10.0));
    }
}
```

**Comment by faustus123** [comment]
Your example looks to be for the case when two algorithms live in a single class (or one algorithm with a flag or parameter to modify it). The tag feature was intended for the case when a different author writes a factory using a completely different algorithm to produce objects of type SomeType without ever having to touch the original factory code.

Take a look at the Tutorial example where in Tutorial.cc there is a call:

app->Add(new JFactoryGeneratorT<SimpleClusterFactory>);

Suppose I want to add a tagged factory whose classname is SimpleClusterFactory_ALT1. I could add it using the a syntax like Dmitry is suggesting with:

app->Add( new JFactoryGeneratorT<SimpleClusterFactory_ALT1>("ALT1") );

The JANA-1 style used a virtual method so the tag was buried in the SimpleClusterFactory_ALT1 subclass as opposed to being a settable member of the JFactory base class. This change does mean that the tag string must be passed in when the JFactory-derived object is constructed.

I think I'm warming up to Dmitry's suggestion that it can be passed into the generator as shown in the line above. The syntax looks pretty clean and I would guess having a tag member of the JFactoryGeneratorT specialization class would not be an issue. No?

So one other complication to throw out there: I really like how we no longer require the user to subclass JFactoryGenerator and instead take care of it with a template. What if we extended this idea to a method of JApplication so we could write the above lines like:

app->Add<SimpleClusterFactory>();
app->Add<SimpleClusterFactory_ALT1>("ALT1");

Could we check in the templated Add method that "T" inherits from JFactory and then automatically instantiate a new JFactoryGeneratorT<SimpleClusterFactory>? This wouldn't remove the ability for users to add their own custom factory generator, but would provide a much more compact, yet readable syntax. At least to me, this looks much cleaner than what we have at the moment. Mainly because there are no nested brackets/parentheses.

We could also generalize it with variadic arguments for the factory constructor to cover the case Nathan describes in the previous comment, though maybe that is a can of worms.

**Comment by nathanwbrei** [comment]
Tagged factory generators are trivial now that we have JFactory::SetTag. Adding a JApplication::Add<MyFactory> would be very nice, but isn't doable yet because it would make the dependency graph cyclic: JApplication.h -> JFactoryGenerator.h -> JFactorySet.h -> JFactoryT.h -> JApplication.h.
