### ISSUE TITLE
true/false as valid user inputs of the parameter manager

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#75]
I would propose parsing rules
on = 1
off = 0
true = 1
false = 0

thus:

```
-Pparam=1
-Pparam=on
-Pparam=true

# OR
-Pparam=0
-Pparam=off
-Pparam=false
```
would be valid and working 

P.S. Look at EIC slack for initial issue

**Comment by faustus123** [comment]
I agree that this would probably avoid many problems the user would encounter with boolean type flags. I guess to make this work, we would need to check if the type being passed to SetDefaultParameter is an integer or bool and if so, map certain magic strings for the input parameter to appropriate values. It would make the code less "clean", but would add a more expected behavior for the users. I'll let Nathan comment.

**Comment by nathanwbrei** [comment]
I'm not opposed to this precise request, but I do see it as a slippery slope. Each individual feature request seems easy and helpful, but when put together there are way more edge cases and ambiguities and unanticipated consequences than one would expect. If we decided we wanted even more user-friendly magic like this I would argue for using an existing library e.g. a YAML parser instead.

**Comment by nathanwbrei** [comment]
I'm moving this discussion to pull request #78.
