### ISSUE TITLE
Jana build fails if there is no distutils installed

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#98]
Now it is about master branch:

```
CMake Warning at src/plugins/streamDet/CMakeLists.txt:31 (message):
  Skipping target `streamDet` due to missing ZeroMQ or ROOT dependencies


-- Found ZeroMQ: /usr/lib/x86_64-linux-gnu/libzmq.so  
-- pybind11 v2.6.1 
-- Found PythonInterp: /usr/bin/python3.8 (found version "3.8.7") 
CMake Error at src/python/externals/pybind11-2.6.1/tools/FindPythonLibsNew.cmake:131 (message):
  Python config failure:

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

  ImportError: cannot import name 'sysconfig' from 'distutils'
  (/usr/lib/python3.8/distutils/_init_.py)

Call Stack (most recent call first):
  src/python/externals/pybind11-2.6.1/tools/pybind11Tools.cmake:38 (find_package)
  src/python/externals/pybind11-2.6.1/tools/pybind11Common.cmake:201 (include)
  src/python/externals/pybind11-2.6.1/CMakeLists.txt:169 (include)


-- Configuring incomplete, errors occurred!
See also "/home/microway/install_escalate/jana/build/master/CMakeFiles/CMakeOutput.log".
See also "/home/microway/install_escalate/jana/build/master/CMakeFiles/CMakeError.log".
Execution done. Return code = 1

ERROR
: Command return code != 0. COMMAND CONTENT:
cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/home/microway/install_escalate/jana/jana-master -DCMAKE_CXX_STANDARD=17   /home/microway/install_escalate/jana/src/master&& cmake --build . -- -j 4&& cmake --build . --target install
```

**Comment by nathanwbrei** [comment]
This [stackoverflow](https://stackoverflow.com/questions/63823964/importerror-cannot-import-name-sysconfig-from-distutils-usr-lib-python3-8) post suggests the problem might be that the python yum package and python-distutils yum package got out of sync with each other. Regardless, pybind11 has broken the build before and I'm confident it will continue breaking the build in the future. I don't think we should be concerning ourselves with debugging the platform's python issues when very few people are using the python functionality to begin with. 

For now I'm going to make the python dependent build targets opt-in, and document somewhere exactly how the user is supposed to configure their system for them to work. While I'm at it I'd also like to make pybind11 be a git submodule so that we don't have to lug around its code in its entirety.
